### PR TITLE
fix static build

### PR DESCRIPTION
**Pull request by m-kuhn**

### CODE REVIEW

**Comment by hobu** [comment]
I will merge this when the CI is ✅

**Comment by mwtoews** [comment]
What does this fix? Nothing is wrong from what I see.

**Comment by m-kuhn** [comment]
From what I could see, currently dlls are built even when building statically. I did not review in depth and ported pretty much 1:1 from https://github.com/libspatialindex/libspatialindex/pull/223

**Comment by mwtoews** [comment]
For the record, using the current master branch I do not see any DLLs generated or installed with the following with MSVC2019:

    cmake -GNinja -DBUILD_SHARED_LIBS=OFF -DCMAKE_INSTALL_PREFIX=F:\temp\inst ..

but let's follow-up any further discussion in #223

**Pull request closed without merging**
