### PR TITLE
CMake: use relative RPATH options for macOS

### PR DESCRIPTION
**Pull request by mwtoews**
Possible solution towards #190

This is the same CMake RPATH options used for both PDAL and PROJ.

### CODE REVIEW

**Comment by mwtoews** [comment]
This doesn't seem easy, so giving up for now.

**Comment by hobu** [comment]
> This doesn't seem easy, so giving up for now.

Nope. It's super annoying.

**Comment by hobu** [comment]
@mwtoews should libspatialindex be following what you did https://github.com/OSGeo/PROJ/pull/3009 ?

**Comment by mwtoews** [comment]
Probably, sticking with defaults seems to annoy fewer people. Is a release imminent?

**Comment by hobu** [comment]
> Is a release imminent?

No, I was just trying to get CI and stuff healthy. An Rtree release is imminent though

**Pull request closed without merging**
