### PR TITLE
modify C API internals to match C API definition in headers (fixes #92)

### PR DESCRIPTION
**Pull request by hobu**
See #92 and #93  for discussion.

This PR implements fixes to API internals rather than changing the public API.

### CODE REVIEW

**Comment by miklos1** [comment]
Is this going to be merged?

**Comment by hobu** [comment]
Yes, but I was waiting on verification from @rosshemsley as requested in #92

**Comment by miklos1** [comment]
Thanks for the information!

**Comment by miklos1** [comment]
Prod

**Comment by hobu** [comment]
@miklos1 did this cure issues for you?

**Pull request merged**
