### PR TITLE
Add an alternative bulk-insert API

### PR DESCRIPTION
**Pull request by FreddieWitherden**
This is intended to gather feedback.  I've mocked up a bulk insert API which takes a set of array pointers as opposed to a function pointer.  This requires some very minor refactoring but nothing too major.  Feedback on the overall approach would be appreciated.  I've tried to make the API reasonably flexible by including strides which should allow most reasonable data structures (AoS or SoA) to be directly ingested.

Assuming everything checks out I'll wire everything up for Python RTree.

### CODE REVIEW

**Comment by FreddieWitherden** [comment]
@hobu Are you okay with the overall API?  Specifically, that we do not support data for the inserted items.

**Comment by hobu** [comment]
> Are you okay with the overall API? 

Yep. Clustered storage isn't really the strong suit of libspatialindex anyway. If the user wants clustered storage they'll need to insert one-at-a-time.

**Comment by FreddieWitherden** [comment]
Sounds good.  Let me know what is needed test wise (I'm not familiar with that part of the code).

Also, is there a timeline for the next release?  The Python RTree code really benefits from this API and so it would be nice if a release could be done so we can take advantage of it.

**Comment by hobu** [comment]
The RTree tests probably need to work with both old and new releases of libspatialindex. 

> Let me know what is needed test wise

If you can codger something up that runs with the CI it would help protect it from rotting. There isn't great tests in this library, but the place you should add them going forward is the gtest code at https://github.com/libspatialindex/libspatialindex/blob/main/test/gtest/sidx_api_test.h

> Also, is there a timeline for the next release? 

When you think you're ready 😄

**Comment by FreddieWitherden** [comment]
> When you think you're ready 😄

I have some bulk-query code that I would like to get sorted and upstreamed.  Then I think we are good to go with a release assuming no one else has an objection.

**Comment by FreddieWitherden** [comment]
Are we okay to merge?

**Comment by hobu** [comment]
> Are we okay to merge?

I was waiting for you 😄 

You are clear to merge and work the project as you see fit @FreddieWitherden. Please milestone your PRs to 2.1 so it is convenient to roll up the release, and please ping me when you are ready to issue it, and I'll show you how to do that too.

**Pull request merged**
