### PR TITLE
Fix 'redefining' warning on __THROW and __NTH

### PR DESCRIPTION
**Pull request by mortezaipo**

### CODE REVIEW

**Comment by mortezaipo** [comment]
I'm developing in Linux and I don't know what's going on on Windows. I'm going to install a Windows on local VM. Is there any instruction or guideline exists that I compile and test mine changes on Windows? Would you please guide me?

**Comment by mortezaipo** [comment]
@hobu , would you please guide me what should I do?

**Comment by hobu** [comment]
Adjust the appveyor configuration as described in https://www.appveyor.com/docs/how-to/rdp-to-build-worker/ to allow you to log in via remote desktop. This is probably the simplest way to get a vm that you can iterate and work in. It times out in 60 minutes though, but it should give you enough time to decipher the issue. If you don't get to this in the next few weeks, I am likely to come along and clean it up, but I don't have time just now.

**Comment by mortezaipo** [comment]
@hobu Thank you so much.

**Comment by mortezaipo** [comment]
@hobu , we've found the issue. I'll update the pull request.

**Comment by mortezaipo** [comment]
@hobu , fixed ;)

**Pull request merged**
