### PR TITLE
Replace all 'byte' to 'uint8_t' type

### PR DESCRIPTION
**Pull request by mortezaipo**
All 'byte' replaced with 'uint8_t' to make it compatible with C++17.

### CODE REVIEW

**Comment by hobu** [comment]
Oops, windows doesn't like this.

https://ci.appveyor.com/project/hobu/libspatialindex/builds/22835627

**Comment by mortezaipo** [comment]
Yes, I think it's for the different pull request: https://github.com/libspatialindex/libspatialindex/pull/141

**Comment by hobu** [comment]
sorry. Catch you there.

**Comment by mortezaipo** [comment]
I'm going to update it ;)

**Pull request merged**
